-- DiceMaster stopped being a built-in document theme: it is one brand's look (DiceMaster.io),
-- not Slopify's. An install that has already used the Document stage gets it back as a saved
-- Library → Documents theme with exactly the values it had, so it can still be picked for new
-- projects. Projects saved with it keep drawing with it either way (legacy-dicemaster.ts).
-- A fresh install gets nothing, and an existing theme of that name is left alone.
-- The JSON below is legacyDiceMasterTheme; legacy-dicemaster.test.ts holds the two equal.
INSERT INTO document_themes (id, name, values_json, created_at, updated_at)
SELECT 'legacy-dicemaster', 'DiceMaster',
  '{"page":{"format":"a4","margin":22,"contentTop":32},"background":{"image":"parchment","color":"#f5ebd7"},"colors":{"heading":"#8c1e14","text":"#000000","muted":"#50463c","faint":"#786e5f"},"fonts":{"body":{"family":"Cinzel","style":"normal","letterSpacing":0.01},"strong":{"family":"Cinzel","style":"bold","letterSpacing":0.02},"emphasis":{"family":"times","style":"italic","letterSpacing":0},"heading":{"family":"Cinzel","style":"bold","letterSpacing":0.02},"dramatic":{"family":"Cinzel","style":"black","letterSpacing":0.03},"decorative":{"family":"Cinzel","style":"medium","letterSpacing":0.015},"dropCap":{"family":"Cinzel","style":"black","letterSpacing":0},"footer":{"family":"times","style":"normal","letterSpacing":0}},"sizes":{"brand":31,"title":22,"section":19,"heading":17,"subheading":13,"body":10.5,"footer":9,"meta":10},"spacing":{"bodyLine":8,"headingLine":11,"subheadingLine":9,"paragraphGap":0.5,"headingGap":1,"itemGap":0.2,"listIndent":6,"quoteIndent":8,"ruleWidth":30},"dropCap":{"enabled":true,"lines":3,"scale":3,"gap":4,"minLength":50,"minRoom":0.25},"titlePage":{"brandY":60,"taglineOffset":10,"titleY":80,"titleLine":10,"metaOffset":20,"metaLine":10,"showDate":true,"showWordCount":true,"cover":{"enabled":true,"gap":6,"maxHeight":110}},"contents":{"enabled":true,"title":"Table of Contents","depth":2,"titleOffset":20,"firstEntryOffset":40,"line":8,"indent":5},"header":{"enabled":true,"top":15,"maxTitleCharacters":35},"footer":{"enabled":true,"bottom":10,"reserve":15,"text":"Page {page}"},"brand":{"name":"DiceMaster.io","url":"https://dicemaster.io/","tagline":"Let us Handle the Crunch, You Focus on the Story","linkLabel":"Visit DiceMaster.io"},"metadata":{"author":"Created with DiceMaster.io","subject":"{title} - Powered by DiceMaster.io","keywords":"D&D, DnD, Dungeons and Dragons, lore, script, tabletop, RPG, TTRPG, DiceMaster.io","creator":"DiceMaster.io - The AI-Powered Virtual Tabletop"},"sources":{"enabled":true,"title":"Sources Consulted","titleOffset":20,"bodyOffset":40,"line":8,"gap":2},"endPage":{"enabled":true,"title":"About DiceMaster.io","titleOffset":20,"bodyOffset":40,"lines":["About DiceMaster.io:","• Character Engine - Form-driven creation with automatic leveling","• Automated Rules Engine - D&D mechanics and spells run automatically","• AI-Generated NPCs - Instant personalities with full stat blocks","• Granular Inventory Tracking - Live gear & condition management","• Real-Time Rule Guidance - Context-aware clarifications","• Dynamic Storytelling AI - On-the-fly narration & dialogue","• True-Physics Dice - RNG-driven rolls with animated suspense","• Cinematic Combat Module - Positional tracking & narrative summaries","• Voice Commands - Seamless STT/TTS multimodal interaction","• AI Dungeon Master Layer - Rules adjudication & encounter balancing"],"showDocumentDetails":true,"link":{"text":"Visit DiceMaster.io","url":"https://dicemaster.io/"},"closing":"Experience the future of tabletop RPGs!"}}',
  strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE EXISTS (SELECT 1 FROM stages WHERE kind = 'document' AND source <> 'off')
  AND NOT EXISTS (SELECT 1 FROM document_themes WHERE lower(name) = 'dicemaster');
